version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=sqlite:///./lasavopay.db
      - NODIT_SECRET=${NODIT_SECRET}
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
  telegram-bot:
    build: ./telegram-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
